#!/bin/bash

# Apple XCFramework build: iOS device + iOS Simulator + Mac Catalyst
# Produces a single Weiss.xcframework; Xcode picks the slice by SDK.

set -e

export PATH="$HOME/go/bin:$PATH"

WEISS_H_CONTENT='
// Objective-C API for talking to the following Go packages
//
//	weiss
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Weiss_FRAMEWORK_H__
#define __Weiss_FRAMEWORK_H__

#include "Weiss.objc.h"
#include "Universe.objc.h"

#endif
'

normalize_slice() {
  local slice_dir="$1"
  local gomobile_fw_name="$2"   # e.g. Weiss-Ios.framework
  local gomobile_bin_name="$3"  # e.g. Weiss-Ios
  local min_os="$4"             # e.g. 13.0 or 15.0

  local old_fw="${slice_dir}/${gomobile_fw_name}"
  local new_fw="${slice_dir}/Weiss.framework"

  if [ ! -d "$old_fw" ]; then
    echo "ERROR: expected framework not found: $old_fw" >&2
    ls -la "$slice_dir" >&2 || true
    exit 1
  fi

  if [ -d "$new_fw" ] && [ "$old_fw" != "$new_fw" ]; then
    rm -rf "$new_fw"
  fi
  if [ "$old_fw" != "$new_fw" ]; then
    mv "$old_fw" "$new_fw"
  fi

  # Versioned (macOS-style) frameworks: binary under Versions/A/
  if [ -d "${new_fw}/Versions/A" ]; then
    if [ -f "${new_fw}/Versions/A/${gomobile_bin_name}" ] && [ "${gomobile_bin_name}" != "Weiss" ]; then
      mv "${new_fw}/Versions/A/${gomobile_bin_name}" "${new_fw}/Versions/A/Weiss"
    fi
    # Always repair root / Current symlinks: gomobile leaves Weiss-Maccatalyst -> ... which breaks after rename.
    rm -f "${new_fw}/${gomobile_bin_name}" "${new_fw}/Weiss"
    ln -sfn "Versions/Current/Weiss" "${new_fw}/Weiss"
    if [ ! -e "${new_fw}/Versions/Current" ]; then
      ln -sfn "A" "${new_fw}/Versions/Current"
    fi
  fi

  # Flat (iOS) frameworks: binary at framework root
  if [ -f "${new_fw}/${gomobile_bin_name}" ] && [ "${gomobile_bin_name}" != "Weiss" ]; then
    mv "${new_fw}/${gomobile_bin_name}" "${new_fw}/Weiss"
  fi

  for plist in "${new_fw}/Info.plist" "${new_fw}/Resources/Info.plist" "${new_fw}/Versions/A/Resources/Info.plist"; do
    if [ -f "$plist" ]; then
      plutil -replace MinimumOSVersion -string "$min_os" "$plist" 2>/dev/null || true
      plutil -replace CFBundleExecutable -string "Weiss" "$plist" 2>/dev/null || true
      plutil -replace CFBundleIdentifier -string "Weiss" "$plist" 2>/dev/null || true
    fi
  done

  local headers="${new_fw}/Headers"
  if [ -d "${new_fw}/Versions/A/Headers" ]; then
    headers="${new_fw}/Versions/A/Headers"
  fi
  printf '%s\n' "$WEISS_H_CONTENT" > "${headers}/Weiss.h"

  local modulemap="${new_fw}/Modules/module.modulemap"
  if [ -d "${new_fw}/Versions/A/Modules" ]; then
    modulemap="${new_fw}/Versions/A/Modules/module.modulemap"
  fi
  # Force module name + umbrella header to Weiss
  cat > "$modulemap" << 'EOF'
framework module "Weiss" {
  umbrella header "Weiss.h"

  export *
  module * { export * }
}
EOF

  echo "  ✓ normalized $(basename "$slice_dir") -> Weiss.framework"
}

echo "开始构建 Weiss.xcframework (iOS + Simulator + Mac Catalyst)..."

echo "清理旧的构建产物..."
rm -rf build
rm -rf Weiss.xcframework
mkdir -p build

echo "构建 iOS 设备版本 (arm64)..."
CGO_ENABLED=1 GOOS=ios GOARCH=arm64 \
  gomobile bind -target=ios -iosversion=13.0 -o build/Weiss-ios.xcframework .

echo "构建 iOS 模拟器版本 (arm64 + x86_64)..."
CGO_ENABLED=1 \
  gomobile bind -target=iossimulator -iosversion=13.0 -o build/Weiss-iossimulator.xcframework .

# Xcode 15+/26 reject -target *-apple-ios13.0-macabi; Catalyst needs >= 15.0.
echo "构建 Mac Catalyst 版本 (iosversion=15.0)..."
CGO_ENABLED=1 \
  gomobile bind -target=maccatalyst -iosversion=15.0 -o build/Weiss-maccatalyst.xcframework .

# Pick slices by identifier (do not use unordered find | head)
IOS_SLICE=$(find build/Weiss-ios.xcframework -mindepth 1 -maxdepth 1 -type d -name 'ios-arm64' | head -1)
SIM_SLICE=$(find build/Weiss-iossimulator.xcframework -mindepth 1 -maxdepth 1 -type d -name '*simulator*' | head -1)
MAC_SLICE=$(find build/Weiss-maccatalyst.xcframework -mindepth 1 -maxdepth 1 -type d -name '*maccatalyst*' | head -1)

if [ -z "$IOS_SLICE" ] || [ -z "$SIM_SLICE" ] || [ -z "$MAC_SLICE" ]; then
  echo "ERROR: failed to locate gomobile slices:" >&2
  echo "  IOS_SLICE=$IOS_SLICE" >&2
  echo "  SIM_SLICE=$SIM_SLICE" >&2
  echo "  MAC_SLICE=$MAC_SLICE" >&2
  find build -maxdepth 3 -type d >&2
  exit 1
fi

echo "Detected slices:"
echo "  iOS:  $IOS_SLICE"
echo "  Sim:  $SIM_SLICE"
echo "  Mac:  $MAC_SLICE"

# Framework may be at slice root or under Versions (Catalyst)
find_fw() {
  local slice="$1"
  local fw
  fw=$(find "$slice" -maxdepth 1 -name '*.framework' | head -1)
  if [ -z "$fw" ]; then
    fw=$(find "$slice" -maxdepth 2 -name '*.framework' | head -1)
  fi
  echo "$fw"
}

IOS_FW_PATH=$(find_fw "$IOS_SLICE")
SIM_FW_PATH=$(find_fw "$SIM_SLICE")
MAC_FW_PATH=$(find_fw "$MAC_SLICE")
IOS_FW=$(basename "$IOS_FW_PATH")
SIM_FW=$(basename "$SIM_FW_PATH")
MAC_FW=$(basename "$MAC_FW_PATH")

echo "修正模块名..."
# Pre-normalize module maps before create-xcframework (names vary by gomobile version)
find build -name module.modulemap | while read -r mm; do
  sed -i '' 's/framework module "Weiss[^"]*"/framework module "Weiss"/' "$mm" || true
done

echo "创建统一的 XCFramework..."
echo "  frameworks: $IOS_FW_PATH | $SIM_FW_PATH | $MAC_FW_PATH"
xcodebuild -create-xcframework \
    -framework "$IOS_FW_PATH" \
    -framework "$SIM_FW_PATH" \
    -framework "$MAC_FW_PATH" \
    -output Weiss.xcframework

echo "统一框架名称和结构..."
# After create-xcframework, library identifiers keep gomobile names; rename each slice
for slice in Weiss.xcframework/*/; do
  [ -d "$slice" ] || continue
  id=$(basename "$slice")
  case "$id" in
    Info.plist) continue ;;
  esac
  fw=$(find "$slice" -maxdepth 1 -name '*.framework' | head -1)
  [ -n "$fw" ] || continue
  fw_name=$(basename "$fw")
  bin_name="${fw_name%.framework}"
  min_os="13.0"
  if echo "$id" | grep -qi 'maccatalyst\|macos'; then
    min_os="15.0"
  fi
  normalize_slice "$slice" "$fw_name" "$bin_name" "$min_os"
done

echo "更新 xcframework Info.plist 中的 LibraryPath / BinaryPath..."
python3 - <<'PY'
import plistlib
from pathlib import Path
plist_path = Path("Weiss.xcframework/Info.plist")
with plist_path.open("rb") as f:
    data = plistlib.load(f)
for lib in data.get("AvailableLibraries", []):
    lib["LibraryPath"] = "Weiss.framework"
    # Prefer non-versioned path; versioned frameworks still expose Weiss via symlink
    lib["BinaryPath"] = "Weiss.framework/Weiss"
with plist_path.open("wb") as f:
    plistlib.dump(data, f, sort_keys=False)
print("  ✓ Info.plist updated")
for lib in data["AvailableLibraries"]:
    print("   ", lib.get("LibraryIdentifier"), lib.get("SupportedPlatform"), lib.get("SupportedPlatformVariant"))
PY

echo "清理临时文件..."
rm -rf build

echo "✅ Weiss.xcframework 构建完成！"
echo "支持的平台："
echo "  - iOS 设备: arm64"
echo "  - iOS 模拟器: arm64 / x86_64"
echo "  - Mac Catalyst: arm64 / x86_64 (若 gomobile 产出 fat)"

echo ""
echo "验证架构信息："
find Weiss.xcframework -name Weiss -type f | while read -r bin; do
  echo "-- $bin"
  lipo -info "$bin" 2>/dev/null || file "$bin"
done
