#!/bin/bash

# iOS xcframework 构建脚本
# 支持 iOS 设备（arm64）和模拟器（arm64 + x86_64）

set -e

# 设置 PATH，确保能找到 gomobile 和 gobind
export PATH="$HOME/go/bin:$PATH"

echo "开始构建 Weiss.xcframework..."

# 清理旧的构建产物
echo "清理旧的构建产物..."
rm -rf build
rm -rf Weiss.xcframework
mkdir -p build

# 构建 iOS 设备版本（arm64）
# 注意：gomobile 会生成包含 Weiss-Ios.framework 的临时 xcframework
# 我们稍后会将其重命名为统一的 Weiss.framework
echo "构建 iOS 设备版本 (arm64)..."
CGO_ENABLED=1 GOOS=ios GOARCH=arm64 \
  gomobile bind -target=ios -o build/Weiss-ios.xcframework .

# 构建 iOS 模拟器版本（arm64 + x86_64）
# 注意：gomobile 会生成包含 Weiss-Iossimulator.framework 的临时 xcframework
# 我们稍后会将其重命名为统一的 Weiss.framework
echo "构建 iOS 模拟器版本 (arm64 + x86_64)..."
CGO_ENABLED=1 \
  gomobile bind -target=iossimulator -o build/Weiss-iossimulator.xcframework .

# 修正模块名为 "Weiss" 以保持代码兼容性
echo "修正模块名..."
sed -i '' 's/framework module "Weiss-Ios"/framework module "Weiss"/' \
    build/Weiss-ios.xcframework/ios-arm64/Weiss-Ios.framework/Modules/module.modulemap
sed -i '' 's/framework module "Weiss-Iossimulator"/framework module "Weiss"/' \
    build/Weiss-iossimulator.xcframework/ios-arm64_x86_64-simulator/Weiss-Iossimulator.framework/Modules/module.modulemap

# 创建统一的 XCFramework
echo "创建统一的 XCFramework..."
xcodebuild -create-xcframework \
    -framework build/Weiss-ios.xcframework/ios-arm64/Weiss-Ios.framework \
    -framework build/Weiss-iossimulator.xcframework/ios-arm64_x86_64-simulator/Weiss-Iossimulator.framework \
    -output Weiss.xcframework

# 统一框架名称和结构，使其与旧的格式一致
echo "统一框架名称和结构..."

# 定义框架目录路径
IOS_FRAMEWORK_DIR="Weiss.xcframework/ios-arm64"
SIMULATOR_FRAMEWORK_DIR="Weiss.xcframework/ios-arm64_x86_64-simulator"

# 重命名 iOS 设备框架
if [ -d "$IOS_FRAMEWORK_DIR/Weiss-Ios.framework" ]; then
    mv "$IOS_FRAMEWORK_DIR/Weiss-Ios.framework" "$IOS_FRAMEWORK_DIR/Weiss.framework"
    mv "$IOS_FRAMEWORK_DIR/Weiss.framework/Weiss-Ios" "$IOS_FRAMEWORK_DIR/Weiss.framework/Weiss"
    echo "  ✓ 已重命名 iOS 设备框架为 Weiss.framework"
fi

# 重命名 iOS 模拟器框架
if [ -d "$SIMULATOR_FRAMEWORK_DIR/Weiss-Iossimulator.framework" ]; then
    mv "$SIMULATOR_FRAMEWORK_DIR/Weiss-Iossimulator.framework" "$SIMULATOR_FRAMEWORK_DIR/Weiss.framework"
    mv "$SIMULATOR_FRAMEWORK_DIR/Weiss.framework/Weiss-Iossimulator" "$SIMULATOR_FRAMEWORK_DIR/Weiss.framework/Weiss"
    echo "  ✓ 已重命名 iOS 模拟器框架为 Weiss.framework"
fi

# 修复 MinimumOSVersion（gomobile 生成的默认值 100.0 不正确）
echo "修复 MinimumOSVersion..."
plutil -replace MinimumOSVersion -string "13.0" "$IOS_FRAMEWORK_DIR/Weiss.framework/Info.plist"
plutil -replace MinimumOSVersion -string "13.0" "$SIMULATOR_FRAMEWORK_DIR/Weiss.framework/Info.plist"
echo "  ✓ 已修复 MinimumOSVersion"

# 更新框架内部的 Info.plist
echo "更新框架内部的 Info.plist..."
plutil -replace CFBundleExecutable -string "Weiss" "$IOS_FRAMEWORK_DIR/Weiss.framework/Info.plist"
plutil -replace CFBundleIdentifier -string "Weiss" "$IOS_FRAMEWORK_DIR/Weiss.framework/Info.plist"
plutil -replace CFBundleExecutable -string "Weiss" "$SIMULATOR_FRAMEWORK_DIR/Weiss.framework/Info.plist"
plutil -replace CFBundleIdentifier -string "Weiss" "$SIMULATOR_FRAMEWORK_DIR/Weiss.framework/Info.plist"
echo "  ✓ 已更新框架内部的 Info.plist"

# 创建统一的 Weiss.h 头文件
echo "创建统一的 Weiss.h 头文件..."
IOS_HEADERS_DIR="$IOS_FRAMEWORK_DIR/Weiss.framework/Headers"
SIMULATOR_HEADERS_DIR="$SIMULATOR_FRAMEWORK_DIR/Weiss.framework/Headers"

cat > "$IOS_HEADERS_DIR/Weiss.h" << 'EOF'

// Objective-C API for talking to the following Go packages
//
//	weiss
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Weiss_FRAMEWORK_H__
#define __Weiss_FRAMEWORK_H__

#include "Weiss.objc.h"
#include "Universe.objc.h"

#endif
EOF

cat > "$SIMULATOR_HEADERS_DIR/Weiss.h" << 'EOF'

// Objective-C API for talking to the following Go packages
//
//	weiss
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Weiss_FRAMEWORK_H__
#define __Weiss_FRAMEWORK_H__

#include "Weiss.objc.h"
#include "Universe.objc.h"

#endif
EOF
echo "  ✓ 已创建统一的 Weiss.h 头文件"

# 更新模块映射文件，引用统一的 Weiss.h
echo "更新模块映射文件..."
IOS_MODULEMAP="$IOS_FRAMEWORK_DIR/Weiss.framework/Modules/module.modulemap"
SIMULATOR_MODULEMAP="$SIMULATOR_FRAMEWORK_DIR/Weiss.framework/Modules/module.modulemap"

# 替换头文件引用
sed -i '' 's/header "Weiss-Ios.h"/header "Weiss.h"/' "$IOS_MODULEMAP"
sed -i '' 's/header "Weiss-Iossimulator.h"/header "Weiss.h"/' "$SIMULATOR_MODULEMAP"
echo "  ✓ 已更新模块映射文件"

# 更新 xcframework 的 Info.plist，使用统一的框架名称
echo "更新 xcframework 的 Info.plist..."
XCFRAMEWORK_INFO_PLIST="Weiss.xcframework/Info.plist"

# 更新 iOS 设备配置
plutil -replace "AvailableLibraries.0.LibraryPath" -string "Weiss.framework" "$XCFRAMEWORK_INFO_PLIST"
plutil -replace "AvailableLibraries.0.BinaryPath" -string "Weiss.framework/Weiss" "$XCFRAMEWORK_INFO_PLIST"

# 更新 iOS 模拟器配置
plutil -replace "AvailableLibraries.1.LibraryPath" -string "Weiss.framework" "$XCFRAMEWORK_INFO_PLIST"
plutil -replace "AvailableLibraries.1.BinaryPath" -string "Weiss.framework/Weiss" "$XCFRAMEWORK_INFO_PLIST"
echo "  ✓ 已更新 xcframework 的 Info.plist"

# 清理临时构建文件
echo "清理临时文件..."
rm -rf build

echo "✅ Weiss.xcframework 构建完成！"
echo "支持的架构："
echo "  - iOS 设备: arm64"
echo "  - iOS 模拟器: arm64 (Apple Silicon), x86_64 (Intel)"

# 显示架构信息
echo ""
echo "验证架构信息："
lipo -info Weiss.xcframework/ios-arm64/Weiss.framework/Weiss
lipo -info Weiss.xcframework/ios-arm64_x86_64-simulator/Weiss.framework/Weiss
